export interface CityData {
    city: string;
    country: string;
    tzId: string;
}

export const EXTRA_CITIES: CityData[] = [
    // Germany
    { city: 'Hamburg', country: 'Germany', tzId: 'Europe/Berlin' },
    { city: 'Munich', country: 'Germany', tzId: 'Europe/Berlin' },
    { city: 'Frankfurt', country: 'Germany', tzId: 'Europe/Berlin' },
    { city: 'Stuttgart', country: 'Germany', tzId: 'Europe/Berlin' },
    { city: 'Dusseldorf', country: 'Germany', tzId: 'Europe/Berlin' },
    { city: 'Berlin', country: 'Germany', tzId: 'Europe/Berlin' },
    // EET (Eastern European Time)
    { city: 'Athens', country: 'Greece', tzId: 'Europe/Athens' },
    { city: 'Bucharest', country: 'Romania', tzId: 'Europe/Bucharest' },
    { city: 'Helsinki', country: 'Finland', tzId: 'Europe/Helsinki' },
    { city: 'Kyiv', country: 'Ukraine', tzId: 'Europe/Kyiv' },
    { city: 'Sofia', country: 'Bulgaria', tzId: 'Europe/Sofia' },
    { city: 'Tallinn', country: 'Estonia', tzId: 'Europe/Tallinn' },
    { city: 'Riga', country: 'Latvia', tzId: 'Europe/Riga' },
    { city: 'Vilnius', country: 'Lithuania', tzId: 'Europe/Vilnius' },
    // India
    { city: 'Mumbai', country: 'India', tzId: 'Asia/Kolkata' },
    { city: 'Delhi', country: 'India', tzId: 'Asia/Kolkata' },
    { city: 'Bangalore', country: 'India', tzId: 'Asia/Kolkata' },
    { city: 'Hyderabad', country: 'India', tzId: 'Asia/Kolkata' },
    { city: 'Ahmedabad', country: 'India', tzId: 'Asia/Kolkata' },
    { city: 'Chennai', country: 'India', tzId: 'Asia/Kolkata' },
    { city: 'Pune', country: 'India', tzId: 'Asia/Kolkata' },
    // USA
    { city: 'New York City', country: 'United States', tzId: 'America/New_York' },
    { city: 'Brooklyn', country: 'United States', tzId: 'America/New_York' },
    { city: 'Los Angeles', country: 'United States', tzId: 'America/Los_Angeles' },
    { city: 'Chicago', country: 'United States', tzId: 'America/Chicago' },
    { city: 'Houston', country: 'United States', tzId: 'America/Chicago' },
    { city: 'Phoenix', country: 'United States', tzId: 'America/Phoenix' },
    { city: 'Philadelphia', country: 'United States', tzId: 'America/New_York' },
    { city: 'San Antonio', country: 'United States', tzId: 'America/Chicago' },
    { city: 'San Diego', country: 'United States', tzId: 'America/Los_Angeles' },
    { city: 'Dallas', country: 'United States', tzId: 'America/Chicago' },
    { city: 'San Jose', country: 'United States', tzId: 'America/Los_Angeles' },
    { city: 'Austin', country: 'United States', tzId: 'America/Chicago' },
    { city: 'San Francisco', country: 'United States', tzId: 'America/Los_Angeles' },
    { city: 'Seattle', country: 'United States', tzId: 'America/Los_Angeles' },
    { city: 'Miami', country: 'United States', tzId: 'America/New_York' },
    // UK
    { city: 'London', country: 'United Kingdom', tzId: 'Europe/London' },
    { city: 'Birmingham', country: 'United Kingdom', tzId: 'Europe/London' },
    { city: 'Manchester', country: 'United Kingdom', tzId: 'Europe/London' },
    { city: 'Glasgow', country: 'United Kingdom', tzId: 'Europe/London' },
    { city: 'Liverpool', country: 'United Kingdom', tzId: 'Europe/London' },
    // France
    { city: 'Paris', country: 'France', tzId: 'Europe/Paris' },
    { city: 'Marseille', country: 'France', tzId: 'Europe/Paris' },
    { city: 'Lyon', country: 'France', tzId: 'Europe/Paris' },
    { city: 'Toulouse', country: 'France', tzId: 'Europe/Paris' },
    { city: 'Nice', country: 'France', tzId: 'Europe/Paris' },
    // Canada
    { city: 'Toronto', country: 'Canada', tzId: 'America/Toronto' },
    { city: 'Montreal', country: 'Canada', tzId: 'America/Toronto' },
    { city: 'Vancouver', country: 'Canada', tzId: 'America/Vancouver' },
    { city: 'Calgary', country: 'Canada', tzId: 'America/Edmonton' },
    { city: 'Ottawa', country: 'Canada', tzId: 'America/Toronto' },
    // Australia
    { city: 'Sydney', country: 'Australia', tzId: 'Australia/Sydney' },
    { city: 'Melbourne', country: 'Australia', tzId: 'Australia/Melbourne' },
    { city: 'Brisbane', country: 'Australia', tzId: 'Australia/Brisbane' },
    { city: 'Perth', country: 'Australia', tzId: 'Australia/Perth' },
    { city: 'Adelaide', country: 'Australia', tzId: 'Australia/Adelaide' },
    // Japan
    { city: 'Tokyo', country: 'Japan', tzId: 'Asia/Tokyo' },
    { city: 'Yokohama', country: 'Japan', tzId: 'Asia/Tokyo' },
    { city: 'Osaka', country: 'Japan', tzId: 'Asia/Tokyo' },
    { city: 'Nagoya', country: 'Japan', tzId: 'Asia/Tokyo' },
    { city: 'Sapporo', country: 'Japan', tzId: 'Asia/Tokyo' },
    // Brazil
    { city: 'Sao Paulo', country: 'Brazil', tzId: 'America/Sao_Paulo' },
    { city: 'Rio de Janeiro', country: 'Brazil', tzId: 'America/Sao_Paulo' },
    { city: 'Brasilia', country: 'Brazil', tzId: 'America/Sao_Paulo' },
    { city: 'Salvador', country: 'Brazil', tzId: 'America/Bahia' },
    { city: 'Fortaleza', country: 'Brazil', tzId: 'America/Fortaleza' },
    // China
    { city: 'Beijing', country: 'China', tzId: 'Asia/Shanghai' },
    { city: 'Shanghai', country: 'China', tzId: 'Asia/Shanghai' },
    { city: 'Guangzhou', country: 'China', tzId: 'Asia/Shanghai' },
    { city: 'Shenzhen', country: 'China', tzId: 'Asia/Shanghai' },
    { city: 'Chengdu', country: 'China', tzId: 'Asia/Shanghai' },
    // UAE
    { city: 'Dubai', country: 'United Arab Emirates', tzId: 'Asia/Dubai' },
    { city: 'Abu Dhabi', country: 'United Arab Emirates', tzId: 'Asia/Dubai' },
    { city: 'Sharjah', country: 'United Arab Emirates', tzId: 'Asia/Dubai' },
    // Spain
    { city: 'Madrid', country: 'Spain', tzId: 'Europe/Madrid' },
    { city: 'Barcelona', country: 'Spain', tzId: 'Europe/Madrid' },
    { city: 'Valencia', country: 'Spain', tzId: 'Europe/Madrid' },
    { city: 'Seville', country: 'Spain', tzId: 'Europe/Madrid' },
    // Italy
    { city: 'Rome', country: 'Italy', tzId: 'Europe/Rome' },
    { city: 'Milan', country: 'Italy', tzId: 'Europe/Rome' },
    { city: 'Naples', country: 'Italy', tzId: 'Europe/Rome' },
    { city: 'Turin', country: 'Italy', tzId: 'Europe/Rome' },
    // Russia
    { city: 'Moscow', country: 'Russia', tzId: 'Europe/Moscow' },
    { city: 'Saint Petersburg', country: 'Russia', tzId: 'Europe/Moscow' },
    { city: 'Novosibirsk', country: 'Russia', tzId: 'Asia/Novosibirsk' },
    { city: 'Yekaterinburg', country: 'Russia', tzId: 'Asia/Yekaterinburg' },
    // Switzerland
    { city: 'Zurich', country: 'Switzerland', tzId: 'Europe/Zurich' },
    { city: 'Geneva', country: 'Switzerland', tzId: 'Europe/Zurich' },
    { city: 'Basel', country: 'Switzerland', tzId: 'Europe/Zurich' },
    // Netherlands
    { city: 'Amsterdam', country: 'Netherlands', tzId: 'Europe/Amsterdam' },
    { city: 'Rotterdam', country: 'Netherlands', tzId: 'Europe/Amsterdam' },
    { city: 'The Hague', country: 'Netherlands', tzId: 'Europe/Amsterdam' },
    // Singapore
    { city: 'Singapore', country: 'Singapore', tzId: 'Asia/Singapore' },
    // Ireland
    { city: 'Dublin', country: 'Ireland', tzId: 'Europe/Dublin' },
    { city: 'Cork', country: 'Ireland', tzId: 'Europe/Dublin' },
    // South Africa
    { city: 'Johannesburg', country: 'South Africa', tzId: 'Africa/Johannesburg' },
    { city: 'Cape Town', country: 'South Africa', tzId: 'Africa/Johannesburg' },
    { city: 'Durban', country: 'South Africa', tzId: 'Africa/Johannesburg' },
    { city: 'Pretoria', country: 'South Africa', tzId: 'Africa/Johannesburg' },
    // Mexico
    { city: 'Guadalajara', country: 'Mexico', tzId: 'America/Mexico_City' },
    { city: 'Monterrey', country: 'Mexico', tzId: 'America/Monterrey' },
    { city: 'Cancun', country: 'Mexico', tzId: 'America/Cancun' },
    { city: 'Tijuana', country: 'Mexico', tzId: 'America/Tijuana' },
    // Turkey
    { city: 'Istanbul', country: 'Turkey', tzId: 'Europe/Istanbul' },
    { city: 'Ankara', country: 'Turkey', tzId: 'Europe/Istanbul' },
    { city: 'Izmir', country: 'Turkey', tzId: 'Europe/Istanbul' },
    // Thailand
    { city: 'Bangkok', country: 'Thailand', tzId: 'Asia/Bangkok' },
    { city: 'Phuket', country: 'Thailand', tzId: 'Asia/Bangkok' },
    { city: 'Chiang Mai', country: 'Thailand', tzId: 'Asia/Bangkok' },
    // Vietnam
    { city: 'Ho Chi Minh City', country: 'Vietnam', tzId: 'Asia/Ho_Chi_Minh' },
    { city: 'Hanoi', country: 'Vietnam', tzId: 'Asia/Ho_Chi_Minh' },
    { city: 'Da Nang', country: 'Vietnam', tzId: 'Asia/Ho_Chi_Minh' },
    // Indonesia
    { city: 'Jakarta', country: 'Indonesia', tzId: 'Asia/Jakarta' },
    { city: 'Surabaya', country: 'Indonesia', tzId: 'Asia/Jakarta' },
    { city: 'Bandung', country: 'Indonesia', tzId: 'Asia/Jakarta' },
    { city: 'Bali', country: 'Indonesia', tzId: 'Asia/Makassar' },
    // Malaysia
    { city: 'Kuala Lumpur', country: 'Malaysia', tzId: 'Asia/Kuala_Lumpur' },
    { city: 'Penang', country: 'Malaysia', tzId: 'Asia/Kuala_Lumpur' },
    // Argentina
    { city: 'Buenos Aires', country: 'Argentina', tzId: 'America/Argentina/Buenos_Aires' },
    { city: 'Cordoba', country: 'Argentina', tzId: 'America/Argentina/Cordoba' },
    { city: 'Rosario', country: 'Argentina', tzId: 'America/Argentina/Buenos_Aires' },
    // Chile
    { city: 'Santiago', country: 'Chile', tzId: 'America/Santiago' },
    { city: 'Valparaiso', country: 'Chile', tzId: 'America/Santiago' },
    // Colombia
    { city: 'Bogota', country: 'Colombia', tzId: 'America/Bogota' },
    { city: 'Medellin', country: 'Colombia', tzId: 'America/Bogota' },
    { city: 'Cali', country: 'Colombia', tzId: 'America/Bogota' },
    // Peru
    { city: 'Lima', country: 'Peru', tzId: 'America/Lima' },
    { city: 'Cusco', country: 'Peru', tzId: 'America/Lima' },
    // New Zealand
    { city: 'Auckland', country: 'New Zealand', tzId: 'Pacific/Auckland' },
    { city: 'Wellington', country: 'New Zealand', tzId: 'Pacific/Auckland' },
    { city: 'Christchurch', country: 'New Zealand', tzId: 'Pacific/Auckland' },
    // Egypt
    { city: 'Cairo', country: 'Egypt', tzId: 'Africa/Cairo' },
    { city: 'Alexandria', country: 'Egypt', tzId: 'Africa/Cairo' },
    { city: 'Giza', country: 'Egypt', tzId: 'Africa/Cairo' },
    // Israel
    { city: 'Jerusalem', country: 'Israel', tzId: 'Asia/Jerusalem' },
    { city: 'Tel Aviv', country: 'Israel', tzId: 'Asia/Jerusalem' },
    // Poland
    { city: 'Warsaw', country: 'Poland', tzId: 'Europe/Warsaw' },
    { city: 'Krakow', country: 'Poland', tzId: 'Europe/Warsaw' },
    { city: 'Wroclaw', country: 'Poland', tzId: 'Europe/Warsaw' },
];

export const COUNTRY_PRIMARY_TZ: Record<string, string> = {
    'Germany': 'Europe/Berlin',
    'India': 'Asia/Kolkata',
    'United States': 'America/New_York',
    'United Kingdom': 'Europe/London',
    'France': 'Europe/Paris',
    'Canada': 'America/Toronto',
    'Australia': 'Australia/Sydney',
    'Japan': 'Asia/Tokyo',
    'Brazil': 'America/Sao_Paulo',
    'China': 'Asia/Shanghai',
    'United Arab Emirates': 'Asia/Dubai',
    'Spain': 'Europe/Madrid',
    'Italy': 'Europe/Rome',
    'Russia': 'Europe/Moscow',
    'Switzerland': 'Europe/Zurich',
    'Netherlands': 'Europe/Amsterdam',
    'Singapore': 'Asia/Singapore',
    'Mexico': 'America/Mexico_City',
    'Turkey': 'Europe/Istanbul',
    'South Africa': 'Africa/Johannesburg',
    'Thailand': 'Asia/Bangkok',
    'Vietnam': 'Asia/Ho_Chi_Minh',
    'Indonesia': 'Asia/Jakarta',
    'Pakistan': 'Asia/Karachi',
    'Egypt': 'Africa/Cairo',
    'Philippines': 'Asia/Manila',
    'Iran': 'Asia/Tehran',
    'Malaysia': 'Asia/Kuala_Lumpur',
    'Poland': 'Europe/Warsaw',
    'Belgium': 'Europe/Brussels',
    'Sweden': 'Europe/Stockholm',
    'Norway': 'Europe/Oslo',
    'Denmark': 'Europe/Copenhagen',
    'Finland': 'Europe/Helsinki',
    'Ireland': 'Europe/Dublin',
    'Portugal': 'Europe/Lisbon',
    'Austria': 'Europe/Vienna',
    'Greece': 'Europe/Athens',
    'Israel': 'Asia/Jerusalem',
    'New Zealand': 'Pacific/Auckland',
    'Argentina': 'America/Argentina/Buenos_Aires',
    'Chile': 'America/Santiago',
    'Colombia': 'America/Bogota',
    'Peru': 'America/Lima',
    'South Korea': 'Asia/Seoul',
    'Ukraine': 'Europe/Kyiv',
    'Saudi Arabia': 'Asia/Riyadh',
    'Czechia': 'Europe/Prague',
    'Hungary': 'Europe/Budapest',
    'Romania': 'Europe/Bucharest',
    'Bulgaria': 'Europe/Sofia',
    'Estonia': 'Europe/Tallinn',
    'Latvia': 'Europe/Riga',
    'Lithuania': 'Europe/Vilnius',
    'Slovakia': 'Europe/Bratislava',
    'Slovenia': 'Europe/Ljubljana',
    'Croatia': 'Europe/Zagreb',
    'Serbia': 'Europe/Belgrade',
    'Luxembourg': 'Europe/Luxembourg',
    'Iceland': 'Atlantic/Reykjavik',
    'Greenland': 'America/Nuuk',
    'Nigeria': 'Africa/Lagos',
    'Kenya': 'Africa/Nairobi',
    'Morocco': 'Africa/Casablanca',
    'Taiwan': 'Asia/Taipei',
    'Hong Kong': 'Asia/Hong_Kong',
    'Macau': 'Asia/Macau',
    'Bangladesh': 'Asia/Dhaka',
    'Sri Lanka': 'Asia/Colombo',
};
